Odev3/Odev3/Controllers/AdminUrunlerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Odev3.Models;

namespace Odev3.Controllers
{
    public class AdminUrunlerController : Controller
    {
        private DBModelEntities db = new DBModelEntities();

        // GET: AdminUrunler
       
        public ActionResult Index()
        {
            if (Session["Admin"] == null) { return new HttpStatusCodeResult(HttpStatusCode.Unauthorized); }
            if(Session["Admin"].ToString()=="Seara") { }
            else { return new HttpStatusCodeResult(HttpStatusCode.Unauthorized); }
            var urunler = db.Urunler.Include(u => u.AltKategori);
            return View(urunler.ToList());
          
        }

        // GET: AdminUrunler/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urunler urunler = db.Urunler.Find(id);
            if (urunler == null)
            {
                return HttpNotFound();
            }
            return View(urunler);
        }

        // GET: AdminUrunler/Create
        public ActionResult Create()
        {
            ViewBag.AltKategoriID = new SelectList(db.AltKategori, "ID", "AltKategoriAdi");
            return View();
        }

        // POST: AdminUrunler/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,UrunAdi,UrunResmi,Fiyati,StokMiktari,AltKategoriID")] Urunler urunler)
        {
            if (ModelState.IsValid)
            {
                db.Urunler.Add(urunler);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AltKategoriID = new SelectList(db.AltKategori, "ID", "AltKategoriAdi", urunler.AltKategoriID);
            return View(urunler);
        }

        // GET: AdminUrunler/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urunler urunler = db.Urunler.Find(id);
            if (urunler == null)
            {
                return HttpNotFound();
            }
            ViewBag.AltKategoriID = new SelectList(db.AltKategori, "ID", "AltKategoriAdi", urunler.AltKategoriID);
            return View(urunler);
        }

        // POST: AdminUrunler/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,UrunAdi,UrunResmi,Fiyati,StokMiktari,AltKategoriID")] Urunler urunler)
        {
            if (ModelState.IsValid)
            {
                db.Entry(urunler).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AltKategoriID = new SelectList(db.AltKategori, "ID", "AltKategoriAdi", urunler.AltKategoriID);
            return View(urunler);
        }

        // GET: AdminUrunler/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urunler urunler = db.Urunler.Find(id);
            if (urunler == null)
            {
                return HttpNotFound();
            }
            return View(urunler);
        }

        // POST: AdminUrunler/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Urunler urunler = db.Urunler.Find(id);
            db.Urunler.Remove(urunler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Odev3/Odev3/Views/AdminUrunler/Create.cshtml
@model Odev3.Models.Urunler

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Urunler</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.UrunAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrunAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrunAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrunResmi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrunResmi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrunResmi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fiyati, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fiyati, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fiyati, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StokMiktari,"Adet", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StokMiktari, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StokMiktari, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AltKategoriID, "AltKategori Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AltKategoriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AltKategoriID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Odev3/Odev3/Views/AdminUrunler/Delete.cshtml
@model Odev3.Models.Urunler

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Urunler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UrunAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UrunResmi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunResmi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fiyati)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fiyati)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StokMiktari)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StokMiktari)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AltKategori.AltKategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AltKategori.AltKategoriAdi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Odev3/Odev3/Views/AdminUrunler/Details.cshtml
@model Odev3.Models.Urunler

@{
    ViewBag.Title = "Details";
    if (Session["Admin"] != null)
    {
        Layout = "~/Views/Shared/AdminLayout.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";

    }

}

<h2>Details</h2>

<div>
    <h4>Urunler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UrunAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunAdi)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Fiyati)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fiyati)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StokMiktari)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StokMiktari)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AltKategori.AltKategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AltKategori.AltKategoriAdi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Odev3/Odev3/Views/AdminUrunler/Edit.cshtml
@model Odev3.Models.Urunler

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Urunler</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.UrunAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrunAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrunAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrunResmi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrunResmi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrunResmi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fiyati, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fiyati, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fiyati, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StokMiktari, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StokMiktari, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StokMiktari, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AltKategoriID, "AltKategoriID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AltKategoriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AltKategoriID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Odev3/Odev3/Views/AdminUrunler/Index.cshtml
@model IEnumerable<Odev3.Models.Urunler>

@{
    ViewBag.Title = "Admin/Urunler";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<div id="wrapper">

    <!-- LEFT SIDEBAR -->
    <div id="sidebar-nav" class="sidebar">
        <div class="sidebar-scroll">
            <nav>
                <ul class="nav">
                    <li><a href="@Url.Action("Index", "AdminUrunler")"><i class="lnr lnr-home"></i> <span>Ürün Düzenleme</span></a></li>
                    <li><a href="@Url.Action("Index", "AdminMesajlar")"><i class="lnr lnr-code"></i> <span>Mesaj</span></a></li>
                    <li><a href="@Url.Action("Index", "AdminUyeler")"><i class="lnr lnr-home"></i> <span>Üye Düzenleme</span></a></li>
                    <li><a href="@Url.Action("Index", "AdminKategori")"><i class="lnr lnr-home"></i> <span>Kategoriler</span></a></li>
                    <li><a href="@Url.Action("Index", "AdminAltKategori")"><i class="lnr lnr-home"></i> <span>Alt Kategoriler</span></a></li>
                    <li>
                        <a href="@Url.Action("AdminCikis", "AdminLogin")" class="cikis">
                            <i class="fa fa-user"></i>
                            Çıkış Yap
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="main">
        <h2> Ürünler</h2>
        <p>
            @Html.ActionLink("Yeni Ürün Ekle", "Create")
        </p>

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.UrunAdi)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UrunResmi)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Fiyati)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.StokMiktari)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AltKategori.AltKategoriAdi)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.UrunAdi)
                    </td>
                    <td>
                        <img src="@Url.Content(item.UrunResmi)" height="100px" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fiyati)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StokMiktari)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AltKategori.AltKategoriAdi)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>