Odev3/Odev3/Controllers/UyelerController.cs
using Odev3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Odev3.Controllers
{
    public class UyelerController : Controller
    {
        // GET: Uyeler
        DBModelEntities db = new DBModelEntities();
        public ActionResult KayitOl()
        {
            return View();
        }

        public ActionResult UyeGiris()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult UyeOl(Uyeler uye)
        {
            using(DBModelEntities dbModel = new DBModelEntities())
            {
                
                dbModel.Uyeler.Add(uye);
                dbModel.SaveChanges();
            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Registration Successful";


            return RedirectToAction("KayitOl",new Uyeler());
        }

       

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UyeGiris([Bind(Include = "ID,KullaniciAdi,Sifre")] Uyeler uye)
        {

            if (ModelState.IsValid)
            {
                if (db.Uyeler.Any(x => x.KullaniciAdi == uye.KullaniciAdi && x.Sifre == uye.Sifre))
                {
                    Session["KullaniciAdi"] = uye.KullaniciAdi;
                    return RedirectToAction("Index","Home");
                }
            }

            return RedirectToAction("KayitOl");
        }

        public ActionResult Cikis()
        {
            Session["KullaniciAdi"] = null;
            return RedirectToAction("Index","Home");
        }
    }
}

Odev3/Odev3/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>

<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="~/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/vendor/linearicons/style.css">
    <link rel="stylesheet" href="~/assets/vendor/chartist/css/chartist-custom.css">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="~/assets/css/main.css">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="~/assets/css/demo.css">
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <!-- ICONS -->
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" sizes="96x96" href="~/assets/img/favicon.png">
    <!-- WRAPPER -->
    <!-- NAVBAR -->
 
</head>

<body>
    <nav class="navbar navbar-default navbar-fixed-top">

        <div class="container-fluid">
            <h2 class="text-center"> Admin Paneli</h2>
          
        </div>

        

         
    </nav>
    <!-- END NAVBAR -->
        @RenderBody()
</body>
<div class="clearfix"></div>
<footer>
    <div class="container-fluid">
        <p class="copyright">&copy; 2017 <a href="https://www.themeineed.com" target="_blank">Theme I Need</a>. All Rights Reserved.</p>
    </div>
</footer>
 <!-- Javascript -->
<script src="assets/vendor/jquery/jquery.min.js"></script>
<script src="assets/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<script src="assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
<script src="assets/vendor/chartist/js/chartist.min.js"></script>
<script src="assets/scripts/klorofil-common.js"></script>
<script>
	$(function() {
		var data, options;

		// headline charts
		data = {
			labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
			series: [
				[23, 29, 24, 40, 25, 24, 35],
				[14, 25, 18, 34, 29, 38, 44],
			]
		};

		options = {
			height: 300,
			showArea: true,
			showLine: false,
			showPoint: false,
			fullWidth: true,
			axisX: {
				showGrid: false
			},
			lineSmooth: false,
		};

		new Chartist.Line('#headline-chart', data, options);


		// visits trend charts
		data = {
			labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
			series: [{
				name: 'series-real',
				data: [200, 380, 350, 320, 410, 450, 570, 400, 555, 620, 750, 900],
			}, {
				name: 'series-projection',
				data: [240, 350, 360, 380, 400, 450, 480, 523, 555, 600, 700, 800],
			}]
		};

		options = {
			fullWidth: true,
			lineSmooth: false,
			height: "270px",
			low: 0,
			high: 'auto',
			series: {
				'series-projection': {
					showArea: true,
					showPoint: false,
					showLine: false
				},
			},
			axisX: {
				showGrid: false,

			},
			axisY: {
				showGrid: false,
				onlyInteger: true,
				offset: 0,
			},
			chartPadding: {
				left: 20,
				right: 20
			}
		};

		new Chartist.Line('#visits-trends-chart', data, options);


		// visits chart
		data = {
			labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
			series: [
				[6384, 6342, 5437, 2764, 3958, 5068, 7654]
			]
		};

		options = {
			height: 300,
			axisX: {
				showGrid: false
			},
		};

		new Chartist.Bar('#visits-chart', data, options);


		// real-time pie chart
		var sysLoad = $('#system-load').easyPieChart({
			size: 130,
			barColor: function(percent) {
				return "rgb(" + Math.round(200 * percent / 100) + ", " + Math.round(200 * (1.1 - percent / 100)) + ", 0)";
			},
			trackColor: 'rgba(245, 245, 245, 0.8)',
			scaleColor: false,
			lineWidth: 5,
			lineCap: "square",
			animate: 800
		});

		var updateInterval = 3000; // in milliseconds

		setInterval(function() {
			var randomVal;
			randomVal = getRandomInt(0, 100);

			sysLoad.data('easyPieChart').update(randomVal);
			sysLoad.find('.percent').text(randomVal);
		}, updateInterval);

		function getRandomInt(min, max) {
			return Math.floor(Math.random() * (max - min + 1)) + min;
		}

	});
</script>

Odev3/Odev3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <header id="header">
        <!--header-->
        <div class="header_top">
            <!--header_top-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="contactinfo">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                    Dil Seç
                                </button>

                                    <ul class="dropdown-menu">
                                       <li>@Html.ActionLink("Türkçe","ChangeCulture","Home", new { lang = "tr", returnurl = this.Request.RawUrl },null) </li>
                                        <li>@Html.ActionLink("English", "ChangeCulture", "Home", new { lang = "en", returnurl = this.Request.RawUrl }, null) </li>
                                    </ul>
                               
                            </div>
                            @Html.ActionLink(Odev3.Resources.Lang.AdminGirişi, "Index", "AdminLogin", new { @class="btn btn-default usa"})
                            
                         
                           
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="social-icons pull-right">
                            <ul>
                                <li><a href=""><i class="fa fa-facebook"></i></a></li>
                                <li><a href=""><i class="fa fa-twitter"></i></a></li>
                                <li><a href=""><i class="fa fa-linkedin"></i></a></li>
                                <li><a href=""><i class="fa fa-dribbble"></i></a></li>
                                <li><a href=""><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div> 
                </div>
            </div>
        </div><!--/header_top-->

        <div class="header-middle">
            <!--header-middle-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="logo pull-left">
                            <a href="@Url.Action("Index", "Home")">
                               <img src="../Content/logo.png" alt="" /></a>
                                    </div>
                       </div>
                    <div class="col-sm-8">
                        <div class="shop-menu pull-right">
                            <ul>
                            
                               @{ if (Session["KullaniciAdi"] != null)
                                   {
                              
                                <li>
                                    
                                    <a href="@Url.Action("Cikis", "Uyeler")">
                                        <i class="fa fa-user"></i>
                                        Çıkış Yap
                                    </a>
                                </li>
                                   }
                                   else
                                   {
                                    <li>
                                        <i class="fa fa-user"></i>
                                        @Html.ActionLink(Odev3.Resources.Lang.Kayıt, "KayitOl", "Uyeler")
                                                
                                        </li>
                                        <li>
                                            <i class="fa fa-user"></i>
                                            @Html.ActionLink(Odev3.Resources.Lang.Giriş, "UyeGiris", "Uyeler")

                                        </li>

                                   }
                            }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-middle-->

        <div class="header-bottom">
            <!--header-bottom-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="mainmenu pull-left">
                            <ul class="nav navbar-nav collapse navbar-collapse">
                                <li>@Html.ActionLink(Odev3.Resources.Lang.Anasayfa,"Index","Home")</li>
                                <li>@Html.ActionLink(Odev3.Resources.Lang.Ürünler, "Index", "Urunler")</li>
                                <li>@Html.ActionLink(Odev3.Resources.Lang.İletişim, "Index", "Iletisim")</li>
                            </ul>
                        </div>
                    </div>
      
                </div>
            </div>
        </div><!--/header-bottom-->
    </header><!--/header-->

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <div class="col-sm-4">
                   
                    <div class="contactinfo">
                       
                        <ul>
                            <li><h2>İletişim</h2></li>
                            <li><a href=""><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                            <li><a href=""><i class="fa fa-envelope"></i> info@domain.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4 footermenu">
                    <ul class="text-center">
                        <li> <h2>Menüler</h2></li>
                        <li>@Html.ActionLink(Odev3.Resources.Lang.Anasayfa, "Index","Home")</li>
                        <li>@Html.ActionLink(Odev3.Resources.Lang.Ürünler, "Index", "Urunler")</li>
                        <li>@Html.ActionLink(Odev3.Resources.Lang.İletişim, "Index", "Iletisim")</li>
                        <li>@Html.ActionLink(Odev3.Resources.Lang.Kayıt, "KayitOl", "Uyeler")</li>
                        <li>@Html.ActionLink(Odev3.Resources.Lang.Giriş, "UyeGiris", "uyeler")</li>
                    </ul>
                </div>
                <div class="col-sm-4">
                    <div class="social-icons pull-right">
                        <h2 class="text-center">Sosyal Ağlar</h2>
                            <ul>
                                <li><a href=""><i class="fa fa-facebook"></i></a></li>
                                <li><a href=""><i class="fa fa-twitter"></i></a></li>
                                <li><a href=""><i class="fa fa-linkedin"></i></a></li>
                                <li><a href=""><i class="fa fa-dribbble"></i></a></li>
                                <li><a href=""><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                     </div>
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>