Odev3/Odev3/Controllers/AdminMesajlarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Odev3.Models;

namespace Odev3.Controllers
{
    public class AdminMesajlarController : Controller
    {
        private DBModelEntities db = new DBModelEntities();

        // GET: AdminMesajlar
        public ActionResult Index()
        {
            return View(db.Mesajlar.ToList());
        }

        // GET: AdminMesajlar/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mesajlar mesajlar = db.Mesajlar.Find(id);
            if (mesajlar == null)
            {
                return HttpNotFound();
            }
            return View(mesajlar);
        }

        // GET: AdminMesajlar/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminMesajlar/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,KullaniciAdi,Mesaji,Konu,E_Posta")] Mesajlar mesajlar)
        {
            if (ModelState.IsValid)
            {
                db.Mesajlar.Add(mesajlar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mesajlar);
        }

        // GET: AdminMesajlar/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mesajlar mesajlar = db.Mesajlar.Find(id);
            if (mesajlar == null)
            {
                return HttpNotFound();
            }
            return View(mesajlar);
        }

        // POST: AdminMesajlar/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,KullaniciAdi,Mesaji,Konu,E_Posta")] Mesajlar mesajlar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mesajlar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mesajlar);
        }

        // GET: AdminMesajlar/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mesajlar mesajlar = db.Mesajlar.Find(id);
            if (mesajlar == null)
            {
                return HttpNotFound();
            }
            return View(mesajlar);
        }

        // POST: AdminMesajlar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Mesajlar mesajlar = db.Mesajlar.Find(id);
            db.Mesajlar.Remove(mesajlar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Odev3/Odev3/Views/AdminMesajlar/Create.cshtml
@model Odev3.Models.Mesajlar

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Mesajlar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.KullaniciAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KullaniciAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KullaniciAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mesaji, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mesaji, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mesaji, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Konu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Konu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Konu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.E_Posta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.E_Posta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.E_Posta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Odev3/Odev3/Views/AdminMesajlar/Delete.cshtml
@model Odev3.Models.Mesajlar

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Mesajlar</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KullaniciAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KullaniciAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mesaji)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mesaji)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Konu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Konu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.E_Posta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.E_Posta)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Odev3/Odev3/Views/AdminMesajlar/Details.cshtml
@model Odev3.Models.Mesajlar

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Mesajlar</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KullaniciAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KullaniciAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mesaji)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mesaji)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Konu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Konu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.E_Posta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.E_Posta)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Odev3/Odev3/Views/AdminMesajlar/Edit.cshtml
@model Odev3.Models.Mesajlar

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Mesajlar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.KullaniciAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KullaniciAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KullaniciAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mesaji, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mesaji, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mesaji, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Konu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Konu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Konu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.E_Posta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.E_Posta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.E_Posta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Odev3/Odev3/Views/AdminMesajlar/Index.cshtml
@model IEnumerable<Odev3.Models.Mesajlar>

@{
    ViewBag.Title = "Admin/Mesajlar";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div id="wrapper">
  
    <!-- LEFT SIDEBAR -->
    <div id="sidebar-nav" class="sidebar">
        <div class="sidebar-scroll">
            <nav>
                <ul class="nav">
                    <li><a href="@Url.Action("Index", "AdminUrunler")"><i class="lnr lnr-home"></i> <span>Ürün Düzenleme</span></a></li>
                    <li><a href="@Url.Action("Index", "AdminMesajlar")"><i class="lnr lnr-code"></i> <span>Mesaj</span></a></li>
                    <li><a href="@Url.Action("Index", "AdminUyeler")"><i class="lnr lnr-home"></i> <span>Üye Düzenleme</span></a></li>
                    <li><a href="@Url.Action("Index", "AdminKategori")"><i class="lnr lnr-home"></i> <span>Kategoriler</span></a></li>
                    <li><a href="@Url.Action("Index", "AdminAltKategori")"><i class="lnr lnr-home"></i> <span>Alt Kategoriler</span></a></li>
                    <li>
                        <a href="@Url.Action("AdminCikis", "AdminLogin")" class="cikis">
                            <i class="fa fa-user"></i>
                            Çıkış Yap
                        </a>
                    </li>

                </ul>
            </nav>
        </div>
    </div>
    <!-- END LEFT SIDEBAR -->
    <!-- MAIN -->
    <div class="main">
        <h2> Mesajlar</h2>
   
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.KullaniciAdi)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Mesaji)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Konu)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.E_Posta)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.KullaniciAdi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Mesaji)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Konu)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.E_Posta)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </td>
                </tr>
            }

        </table>
    </div>
    <!-- END MAIN -->

</div>
<!-- END WRAPPER -->