Odev3/Odev3/Controllers/AdminAltKategoriController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Odev3.Models;

namespace Odev3.Controllers
{
    public class AdminAltKategoriController : Controller
    {
        private DBModelEntities db = new DBModelEntities();

        // GET: AdminAltKategori
        public ActionResult Index()
        {
            var altKategori = db.AltKategori.Include(a => a.Kategori);
            return View(altKategori.ToList());
        }

        // GET: AdminAltKategori/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AltKategori altKategori = db.AltKategori.Find(id);
            if (altKategori == null)
            {
                return HttpNotFound();
            }
            return View(altKategori);
        }

        // GET: AdminAltKategori/Create
        public ActionResult Create()
        {
            ViewBag.KategoriID = new SelectList(db.Kategori, "ID", "KategoriAdi");
            return View();
        }

        // POST: AdminAltKategori/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,AltKategoriAdi,KategoriID")] AltKategori altKategori)
        {
            if (ModelState.IsValid)
            {
                db.AltKategori.Add(altKategori);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.KategoriID = new SelectList(db.Kategori, "ID", "KategoriAdi", altKategori.KategoriID);
            return View(altKategori);
        }

        // GET: AdminAltKategori/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AltKategori altKategori = db.AltKategori.Find(id);
            if (altKategori == null)
            {
                return HttpNotFound();
            }
            ViewBag.KategoriID = new SelectList(db.Kategori, "ID", "KategoriAdi", altKategori.KategoriID);
            return View(altKategori);
        }

        // POST: AdminAltKategori/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,AltKategoriAdi,KategoriID")] AltKategori altKategori)
        {
            if (ModelState.IsValid)
            {
                db.Entry(altKategori).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KategoriID = new SelectList(db.Kategori, "ID", "KategoriAdi", altKategori.KategoriID);
            return View(altKategori);
        }

        // GET: AdminAltKategori/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AltKategori altKategori = db.AltKategori.Find(id);
            if (altKategori == null)
            {
                return HttpNotFound();
            }
            return View(altKategori);
        }

        // POST: AdminAltKategori/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AltKategori altKategori = db.AltKategori.Find(id);
            db.AltKategori.Remove(altKategori);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Odev3/Odev3/Views/AdminAltKategori/Create.cshtml
@model Odev3.Models.AltKategori

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AltKategori</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.AltKategoriAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AltKategoriAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AltKategoriAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KategoriID, "Kategori Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KategoriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KategoriID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Odev3/Odev3/Views/AdminAltKategori/Delete.cshtml
@model Odev3.Models.AltKategori

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AltKategori</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AltKategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AltKategoriAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori.KategoriAdi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Odev3/Odev3/Views/AdminAltKategori/Details.cshtml
@model Odev3.Models.AltKategori

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>AltKategori</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AltKategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AltKategoriAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori.KategoriAdi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Odev3/Odev3/Views/AdminAltKategori/Edit.cshtml
@model Odev3.Models.AltKategori

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AltKategori</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.AltKategoriAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AltKategoriAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AltKategoriAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KategoriID, "KategoriID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KategoriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KategoriID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Odev3/Odev3/Views/AdminAltKategori/Index.cshtml
@model IEnumerable<Odev3.Models.AltKategori>

@{
    ViewBag.Title = "Admin/AltKategoriler";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Index</h2>
<div id="wrapper">
    <!-- LEFT SIDEBAR -->
    <div id="sidebar-nav" class="sidebar">
        <div class="sidebar-scroll">
            <nav>
                <ul class="nav">
                    <li><a href="@Url.Action("Index", "AdminUrunler")"><i class="lnr lnr-home"></i> <span>Ürün Düzenleme</span></a></li>
                    <li><a href="@Url.Action("Index", "AdminMesajlar")"><i class="lnr lnr-code"></i> <span>Mesaj</span></a></li>
                    <li><a href="@Url.Action("Index", "AdminUyeler")"><i class="lnr lnr-home"></i> <span>Üye Düzenleme</span></a></li>
                    <li><a href="@Url.Action("Index", "AdminKategori")"><i class="lnr lnr-home"></i> <span>Kategoriler</span></a></li>
                    <li><a href="@Url.Action("Index", "AdminAltKategori")"><i class="lnr lnr-home"></i> <span>Alt Kategoriler</span></a></li>
                    <li>
                        <a href="@Url.Action("AdminCikis", "AdminLogin")" class="cikis">
                            <i class="fa fa-user"></i>
                            Çıkış Yap
                        </a>
                    </li>

                </ul>
            </nav>
        </div>
    </div>
    <div class="main">
        <h2> Alt Kategoriler</h2>
        <p>
            @Html.ActionLink("Alt Kategori Ekle", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.AltKategoriAdi)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Kategori.KategoriAdi)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.AltKategoriAdi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kategori.KategoriAdi)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </td>
                </tr>
            }

        </table>
    </div>
    </div>